title: "jekyll-wiki-template"
description: "Ein Minimalbeispiel mit Minimal Mistakes"
baseurl: "/jekyll-wiki-template" # the subpath of your site, e.g. /blog/
url: "https://DominikHirsch.github.io/jekyll-wiki-template"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
  - jekyll-include-cache

search: true
search_full_content: true

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      toc: true
      toc_label: "Inhalt"
      toc_sticky: true
      sidebar:
        nav: docs_sidebar
        auto_expand: true  # alles ausgeklappt

sass:
  sass_dir: _sass