title: "How-To-Wiki"
description: "Ein Minimalbeispiel mit Minimal Mistakes"
baseurl: "/How-To-Wiki" # the subpath of your site, e.g. /blog/
url: "https://DominikHirsch.github.io/How-To-Wiki"

# nur remote_theme verwenden für GitHub Actions
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# lokal: theme aus Gemfile überschreibt remote_theme
theme: minimal-mistakes-jekyll

minimal_mistakes_skin: "air"

plugins:
  - jekyll-include-cache

search: true
search_full_content: true

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      toc: true
      toc_label: "Inhalt"
      toc_sticky: true
